name: CMake Build

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "macOS 14 (Sonoma)",
            os: "macos-14",
            cc: "/usr/bin/clang",
            cxx: "/usr/bin/clang++",
            format: "/usr/local/opt/llvm@14/bin/clang-format",
            tidy: "/usr/local/opt/llvm@14/bin/clang-tidy",
          }
          - {
              name: "Ubuntu 22.0.4 GCC",
              os: "ubuntu-22.04",
              cc: "/usr/bin/gcc",
              cxx: "/usr/bin/g++",
              format: "/usr/bin/clang-format-14",
              tidy: "/usr/bin/clang-tidy-14",
          }

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        working-directory: ${{github.workspace}}
        run: sudo bash ./build_support/packages.sh -y

      - name: Install Dependencies (OSX)
        if: runner.os == 'macOS'
        working-directory: ${{github.workspace}}
        run: bash ./build_support/packages.sh -y

      - name: Configure CMake
        run: CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Unix Makefiles" -DCMAKE_CXX_COMPILER="${{matrix.config.cxx}}" -DCMAKE_C_COMPILER="${{matrix.config.cc}}" -DCMAKE_CXX_STANDARD=17 -DUSE_CPP17=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Check Tests (Ubuntu)
        if: runner.os == 'Linux'
        working-directory: ${{github.workspace}}/build
        run: make build-tests && make check-tests

      - name: Check Tests (OSX)
        if: runner.os == 'macOS'
        working-directory: ${{github.workspace}}/build
        # Disable container overflow checks on OSX
        run: make build-tests && make check-tests